### ISSUE TITLE
SoundCloud: Song title is doubled in the notification popup

### ISSUE THREAD

**Issue by NasaGeek** [kkamperschroer/Musicality#127]
I'll look into fixing it.

**Comment by kkamperschroer** [comment]
That's fantastic. I've been swamped with other work related things, so any help is greatly appreciated it!

If you need any help our guidance please don't hesitate to contact me.

**Comment by NasaGeek** [comment]
Upon further looking, it seems like SoundCloud is a bit of an odd case. The title fix was straightforward, but there doesn't seem to be much of a concept of "artist". The only real data you can get about a song's "source" is where it is playing from (either your stream or another user's page); however this is not a terribly useful piece of data and can sometimes be downright misleading when, for instance, one user has reshared another user's content. I'm thinking of just returning a blank string for the artist.

**Comment by kkamperschroer** [comment]
SoundCloud is definitely a special case, as there is no sure way to determine the artist and track. Every uploader does it differently, making it frustrating to guess. I think your solution from your PR is the best way of handling it instead of trying to do some special logic in the selector.
