### ISSUE TITLE
Pausing Pandora takes far longer than it should when Pandora is in the background

### ISSUE THREAD

**Issue by NasaGeek** [kkamperschroer/Musicality#141]
It looks like Pandora has recently implemented a fade in/fade out effect when pausing and resuming music. The only problem is that this fade happens extremely gradually when Pandora is not in the foreground, resulting in music taking ~30 seconds from the time I pause it to actually stop playing. I strongly suspect it is related to Chrome's treatment of setInterval as detailed in [this SO post](http://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs).

**Comment by kkamperschroer** [comment]
Yeah, I would bet you are right. Interesting problem...

**Comment by NasaGeek** [comment]
Change appears to have been reverted.
