### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by mherrmann3** [kkamperschroer/Musicality#83]
I have two (minor) suggestions:

1. Is it possible to fetch the correct cover in - for example - the [stream](https://soundcloud.com/stream)? (b/c currently, it always uses the FIRST cover). This "issue" also persists when playing music from an artist's page (e.g., [this](https://soundcloud.com/keljet)); then, only the artist's image is used as cover, but not the actual cover of the current song.
2. Can you set the '*thumbs up*' function to the '*like*' button.

Thanks for your time!

**Comment by kkamperschroer** [comment]
Closing since NasaGeek rewrote much of this and it works better now, I believe.
